name: apple-analysis-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - requests
  - pyyaml
  - lightgbm
  - xgboost
  - shap
  - pillow
